"""Bridge bakeoff's config.yaml to engined, which serves every model.

engined owns the pinned llama.cpp build and model lifecycle; bakeoff's job is
to declare its own engine (`llama-bench`) and one chat route per candidate
model plus the judge, then ask the running engined to pick the fragment up.

Exclusivity (holding other engines such as comfy off the box while a
benchmark runs) is bakeoff's own concern -- engined adds nothing for it -- so
this module also owns the optional hold/unhold lifecycle against
`POST /engined/v1/engines/:id/hold`.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Any

import httpx

from bench.config import ConfigError, judge_id

ENGINE_ID = "llama-bench"
FRAGMENT_PATH = Path.home() / ".config" / "engined" / "config.d" / "bakeoff.toml"
_ID_RE = re.compile(r"^[a-z0-9_-]+$")

# A hold lapses on its own if the holder dies; renewing well inside the TTL
# means a slow benchmark cell never lets it lapse mid-run.
HOLD_TTL_S = 600
HOLD_RENEW_INTERVAL_S = 300

MODELS_POLL_INTERVAL_S = 1.0


def _validate_id(model_id: str) -> None:
    if not _ID_RE.match(model_id):
        raise ConfigError(
            f"model id {model_id!r} must match {_ID_RE.pattern} (used as an engined route model id)"
        )


def _validate_gguf_not_mmproj(gguf: str, model_id: str) -> None:
    basename = gguf.rsplit("/", 1)[-1]
    if basename.lower().startswith("mmproj"):
        raise ConfigError(
            f"model {model_id!r}: {basename!r} is an mmproj-* vision "
            "projector, not a standalone text model"
        )


def _toml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        # json's string escaping is a valid TOML basic-string body; this is
        # the "no new dependency" hand-written-TOML path the brief calls for.
        return json.dumps(value)
    raise ConfigError(f"unsupported TOML scalar: {value!r}")


def _route_args(entry: dict[str, Any], server_cfg: dict[str, Any]) -> dict[str, Any]:
    """Every flag bakeoff renders into the container `cmd` today, as route args.

    `parallel = 1`: one slot per model, matching the one-model-in-VRAM
    invariant -- bakeoff never wants llama.cpp batching concurrent callers
    into a resident model's shared ctx pool during a benchmark cell.
    """
    ctx_default = int(server_cfg.get("ctx", 4096))
    args: dict[str, Any] = {
        "parallel": 1,
        "ctx-size": int(entry.get("ctx") or ctx_default),
        "ubatch-size": int(server_cfg.get("ubatch", 512)),
        "n-gpu-layers": int(server_cfg.get("ngl", 99)),
        "cache-type-k": str(server_cfg.get("cache_type_k", "q8_0")),
        "cache-type-v": str(server_cfg.get("cache_type_v", "q8_0")),
    }
    if bool(server_cfg.get("flash_attn", True)):
        args["flash-attn"] = "on"
    if bool(server_cfg.get("jinja", True)):
        args["jinja"] = True
    n_cpu_moe = entry.get("n_cpu_moe")
    if n_cpu_moe is not None:
        args["n-cpu-moe"] = int(n_cpu_moe)
    return args


def _render_route(mid: str, filename: str, args: dict[str, Any]) -> list[str]:
    lines = [
        "[[route]]",
        f'engine = "{ENGINE_ID}"',
        'upstream = "local"',
        f"model = {_toml_scalar(mid)}",
        f"filename = {_toml_scalar(filename)}",
        'role = "chat"',
        "",
        "[route.args]",
    ]
    lines += [f"{k} = {_toml_scalar(v)}" for k, v in args.items()]
    lines.append("")
    return lines


def route_ids(cfg: dict[str, Any]) -> list[str]:
    """Model ids the fragment will declare, in the same order as `render_fragment`."""
    ids = [str(m["id"]) for m in cfg.get("models") or []]
    judge = dict(cfg.get("judge") or {})
    if judge.get("enabled") and judge.get("gguf"):
        ids.append(judge_id(judge))
    return ids


def render_fragment(cfg: dict[str, Any]) -> str:
    """Pure: bakeoff config.yaml -> an engined `config.d/*.toml` fragment.

    One `[[engine]]` (`llama-bench`, `models_max = 1` -- one model in VRAM at
    a time is bakeoff's own invariant) plus one `role = "chat"` route per
    candidate model and the judge.
    """
    engined_cfg = dict(cfg.get("engined") or {})
    server_cfg = dict(cfg.get("server") or {})
    spec_dir = engined_cfg.get("spec_dir")
    models_dir = engined_cfg.get("models_dir")
    if not spec_dir:
        raise ConfigError("engined.spec_dir is required")
    if not models_dir:
        raise ConfigError("engined.models_dir is required")

    lines: list[str] = [
        "# Generated by bench.engined.render_fragment. Do not edit by hand --",
        "# it is overwritten on every run and deleted when the run ends.",
        "[[engine]]",
        f'id = "{ENGINE_ID}"',
        f"spec_dir = {_toml_scalar(str(spec_dir))}",
        f"models_dir = {_toml_scalar(str(models_dir))}",
        f"models_max = {int(engined_cfg.get('models_max', 1))}",
        "",
    ]

    seen: set[str] = set()
    for entry in cfg.get("models") or []:
        if "id" not in entry or "gguf" not in entry:
            raise ConfigError(f"entry missing id/gguf: {entry!r}")
        mid = str(entry["id"])
        _validate_id(mid)
        gguf = str(entry["gguf"])
        _validate_gguf_not_mmproj(gguf, mid)
        if mid in seen:
            raise ConfigError(f"duplicate model id: {mid!r}")
        seen.add(mid)
        lines += _render_route(mid, gguf, _route_args(entry, server_cfg))

    judge = dict(cfg.get("judge") or {})
    if judge.get("enabled") and judge.get("gguf"):
        jid = judge_id(judge)
        _validate_id(jid)
        gguf = str(judge["gguf"])
        _validate_gguf_not_mmproj(gguf, jid)
        if jid in seen:
            raise ConfigError(
                f"judge id {jid!r} collides with a model id — set judge.id to a distinct value"
            )
        lines += _render_route(jid, gguf, _route_args(judge, server_cfg))

    return "\n".join(lines) + "\n"


# --- Lifecycle ---------------------------------------------------------------

_hold_stop: threading.Event | None = None
_hold_thread: threading.Thread | None = None
_held_ids: list[str] = []
_held_engined_url: str | None = None


def _post(engined_url: str, path: str, **params: Any) -> httpx.Response:
    return httpx.post(f"{engined_url}{path}", params=params, timeout=15)


def _check_no_config_error(engined_url: str) -> None:
    """A failed `reload` is silent otherwise: it leaves the prior config running."""
    r = httpx.get(f"{engined_url}/engined/v1/engines", timeout=15)
    r.raise_for_status()
    body = r.json()
    err = body.get("config_error") if isinstance(body, dict) else None
    if err:
        raise RuntimeError(f"engined config_error after reload: {err}")


def _wait_for_models(engined_url: str, model_ids: list[str], timeout_s: float = 60.0) -> None:
    wanted = {f"@/{ENGINE_ID}/{mid}" for mid in model_ids}
    deadline = time.monotonic() + timeout_s
    while True:
        r = httpx.get(f"{engined_url}/openai/v1/models", timeout=15)
        r.raise_for_status()
        listed = {row["id"] for row in r.json().get("data") or []}
        if wanted <= listed:
            return
        if time.monotonic() >= deadline:
            missing = sorted(wanted - listed)
            raise RuntimeError(f"engined never listed: {', '.join(missing)}")
        time.sleep(MODELS_POLL_INTERVAL_S)


def _hold_loop(engined_url: str, ids: list[str], stop: threading.Event) -> None:
    while not stop.wait(HOLD_RENEW_INTERVAL_S):
        for engine_id in ids:
            try:
                _post(engined_url, f"/engined/v1/engines/{engine_id}/hold", seconds=HOLD_TTL_S)
            except Exception as e:
                print(f"[engined-hold-err] {engine_id}: {e}", file=sys.stderr)


def up(cfg: dict[str, Any], engined_url: str) -> None:
    """Write the fragment, reload engined, and wait for every route to be listed.

    Starts the hold-renewal thread only once the reload has been confirmed
    live, so a hold is never taken out for a fragment that failed to apply.
    """
    global _hold_stop, _hold_thread, _held_ids, _held_engined_url

    fragment = render_fragment(cfg)
    FRAGMENT_PATH.parent.mkdir(parents=True, exist_ok=True)
    FRAGMENT_PATH.write_text(fragment)

    subprocess.run(["systemctl", "--user", "reload", "engined"], check=True)
    _check_no_config_error(engined_url)
    _wait_for_models(engined_url, route_ids(cfg))

    hold_ids = list((cfg.get("engined") or {}).get("hold") or [])
    if hold_ids:
        for engine_id in hold_ids:
            _post(engined_url, f"/engined/v1/engines/{engine_id}/hold", seconds=HOLD_TTL_S)
        _held_ids = hold_ids
        _held_engined_url = engined_url
        _hold_stop = threading.Event()
        _hold_thread = threading.Thread(
            target=_hold_loop, args=(engined_url, hold_ids, _hold_stop), daemon=True
        )
        _hold_thread.start()


def down() -> None:
    """Release any holds, delete the fragment, reload. Idempotent; never raises.

    Called from `finally` and `atexit`: a fragment left behind whose GGUF
    later vanishes makes engined refuse to boot, so this must always run.
    """
    global _hold_stop, _hold_thread, _held_ids, _held_engined_url

    if _hold_stop is not None:
        _hold_stop.set()
    if _hold_thread is not None:
        _hold_thread.join(timeout=5)
    _hold_stop = None
    _hold_thread = None

    if _held_engined_url is not None:
        for engine_id in _held_ids:
            try:
                _post(_held_engined_url, f"/engined/v1/engines/{engine_id}/unhold")
            except Exception as e:
                print(f"[engined-down-err] unhold {engine_id}: {e}", file=sys.stderr)
    _held_ids = []
    _held_engined_url = None

    # The second call (atexit after finally) finds nothing to remove, and a
    # reload then would only churn engined for no change.
    if not FRAGMENT_PATH.exists():
        return
    try:
        FRAGMENT_PATH.unlink()
    except Exception as e:
        print(f"[engined-down-err] unlink fragment: {e}", file=sys.stderr)

    try:
        subprocess.run(["systemctl", "--user", "reload", "engined"], check=False)
    except Exception as e:
        print(f"[engined-down-err] reload: {e}", file=sys.stderr)
